### ISSUE TITLE
Deleting clone makes original VM inoperable.

### ISSUE THREAD

**Issue by oliverbock** [pddenhar/esxi-linked-clone#1]
After running clone.sh on ESXi 5.1 I used vSphere to set up and started a new VM using the storage created by clone.sh.  It ran fine.  However when I deleted the cloned VM it also deleted the storage for the original!  Is it possible to avoid this?

Also, presumably the script could be enhanced to run registervm at the end to make the new machine appear in vSphere, but I haven't tried that yet.

**Comment by MikeMcQuaid** [comment]
@pddenhar I reckon this can be closed now `deleteclone.sh` exists as of https://github.com/pddenhar/esxi-linked-clone/pull/2.

**Comment by pddenhar** [comment]
Yup, thanks for the reminder!
